# Form implementation generated from reading ui file 'DockWidget_console.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DockWidget_console(object):
    def setupUi(self, DockWidget_console):
        DockWidget_console.setObjectName("DockWidget_console")
        DockWidget_console.resize(400, 300)
        DockWidget_console.setAllowedAreas(QtCore.Qt.DockWidgetArea.AllDockWidgetAreas)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        DockWidget_console.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_console)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_console)

    def retranslateUi(self, DockWidget_console):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_console.setWindowTitle(_translate("DockWidget_console", "Console"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DockWidget_console = QtWidgets.QDockWidget()
    ui = Ui_DockWidget_console()
    ui.setupUi(DockWidget_console)
    DockWidget_console.show()
    sys.exit(app.exec())
