# Form implementation generated from reading ui file 'DockWidget_postprocessing.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DockWidget_postprocessing(object):
    def setupUi(self, DockWidget_postprocessing):
        DockWidget_postprocessing.setObjectName("DockWidget_postprocessing")
        DockWidget_postprocessing.resize(674, 522)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.dockWidgetContents)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        DockWidget_postprocessing.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_postprocessing)
        QtCore.QMetaObject.connectSlotsByName(DockWidget_postprocessing)

    def retranslateUi(self, DockWidget_postprocessing):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_postprocessing.setWindowTitle(
            _translate("DockWidget_postprocessing", "Postprocessing")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DockWidget_postprocessing = QtWidgets.QDockWidget()
    ui = Ui_DockWidget_postprocessing()
    ui.setupUi(DockWidget_postprocessing)
    DockWidget_postprocessing.show()
    sys.exit(app.exec())
