# Form implementation generated from reading ui file 'DockWidget_sensor_manager.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DockWidget_IMU_client_manager(object):
    def setupUi(self, DockWidget_IMU_client_manager):
        DockWidget_IMU_client_manager.setObjectName("DockWidget_IMU_client_manager")
        DockWidget_IMU_client_manager.resize(809, 420)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_db_name = QtWidgets.QLineEdit(parent=self.dockWidgetContents)
        self.lineEdit_db_name.setInputMask("")
        self.lineEdit_db_name.setObjectName("lineEdit_db_name")
        self.horizontalLayout.addWidget(self.lineEdit_db_name)
        self.pushButton_db_lock = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_db_lock.sizePolicy().hasHeightForWidth()
        )
        self.pushButton_db_lock.setSizePolicy(sizePolicy)
        self.pushButton_db_lock.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../home/vscode/.designer/backup/icons/lock_open.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../home/vscode/.designer/backup/icons/lock_close.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.On,
        )
        self.pushButton_db_lock.setIcon(icon)
        self.pushButton_db_lock.setCheckable(True)
        self.pushButton_db_lock.setChecked(False)
        self.pushButton_db_lock.setObjectName("pushButton_db_lock")
        self.horizontalLayout.addWidget(self.pushButton_db_lock)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_connect_selected = QtWidgets.QPushButton(
            parent=self.dockWidgetContents
        )
        self.pushButton_connect_selected.setCheckable(True)
        self.pushButton_connect_selected.setObjectName("pushButton_connect_selected")
        self.horizontalLayout_2.addWidget(self.pushButton_connect_selected)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_ping_trigger = QtWidgets.QPushButton(
            parent=self.dockWidgetContents
        )
        self.pushButton_ping_trigger.setObjectName("pushButton_ping_trigger")
        self.gridLayout.addWidget(self.pushButton_ping_trigger, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.pushButton_ping_imu = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.pushButton_ping_imu.setCheckable(False)
        self.pushButton_ping_imu.setObjectName("pushButton_ping_imu")
        self.gridLayout.addWidget(self.pushButton_ping_imu, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout.addItem(spacerItem4, 1, 4, 1, 1)
        self.pushButton_reset_trigger = QtWidgets.QPushButton(
            parent=self.dockWidgetContents
        )
        self.pushButton_reset_trigger.setObjectName("pushButton_reset_trigger")
        self.gridLayout.addWidget(self.pushButton_reset_trigger, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_save = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        spacerItem6 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem7)
        DockWidget_IMU_client_manager.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_IMU_client_manager)
        self.pushButton_db_lock.toggled["bool"].connect(self.lineEdit_db_name.setDisabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DockWidget_IMU_client_manager)

    def retranslateUi(self, DockWidget_IMU_client_manager):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_IMU_client_manager.setWindowTitle(
            _translate("DockWidget_IMU_client_manager", "Device Manager")
        )
        self.label.setText(_translate("DockWidget_IMU_client_manager", "Database:"))
        self.lineEdit_db_name.setText(
            _translate("DockWidget_IMU_client_manager", "database.db")
        )
        self.pushButton_connect_selected.setText(
            _translate("DockWidget_IMU_client_manager", "Connect Selected Sensors")
        )
        self.pushButton_ping_trigger.setText(
            _translate("DockWidget_IMU_client_manager", "Ping trigger sensors")
        )
        self.pushButton_ping_imu.setText(
            _translate("DockWidget_IMU_client_manager", "Ping imu sensors")
        )
        self.pushButton_reset_trigger.setText(
            _translate("DockWidget_IMU_client_manager", "Reset trigger sensors")
        )
        self.pushButton_save.setText(
            _translate("DockWidget_IMU_client_manager", "Save current configuration")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DockWidget_IMU_client_manager = QtWidgets.QDockWidget()
    ui = Ui_DockWidget_IMU_client_manager()
    ui.setupUi(DockWidget_IMU_client_manager)
    DockWidget_IMU_client_manager.show()
    sys.exit(app.exec())
