# Form implementation generated from reading ui file 'DockWidget_sequence.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DockWidget_sequence(object):
    def setupUi(self, DockWidget_sequence):
        DockWidget_sequence.setObjectName("DockWidget_sequence")
        DockWidget_sequence.resize(887, 677)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_patient = QtWidgets.QWidget()
        self.tab_patient.setObjectName("tab_patient")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_patient)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab_patient)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_move_id = QtWidgets.QLineEdit(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_move_id.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_move_id.setSizePolicy(sizePolicy)
        self.lineEdit_move_id.setMaximumSize(QtCore.QSize(160, 16777215))
        self.lineEdit_move_id.setMaxLength(32767)
        self.lineEdit_move_id.setClearButtonEnabled(True)
        self.lineEdit_move_id.setObjectName("lineEdit_move_id")
        self.horizontalLayout_7.addWidget(self.lineEdit_move_id)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_7.addItem(spacerItem)
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.comboBox_visit = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox_visit.setObjectName("comboBox_visit")
        self.comboBox_visit.addItem("")
        self.comboBox_visit.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_visit)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_7.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.doubleSpinBox_shoulder_width = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox
        )
        self.doubleSpinBox_shoulder_width.setMinimum(20.0)
        self.doubleSpinBox_shoulder_width.setMaximum(200.0)
        self.doubleSpinBox_shoulder_width.setProperty("value", 60.0)
        self.doubleSpinBox_shoulder_width.setObjectName("doubleSpinBox_shoulder_width")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_shoulder_width)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.doubleSpinBox_ration_min = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleSpinBox_ration_min.setMinimum(0.0)
        self.doubleSpinBox_ration_min.setProperty("value", 0.9)
        self.doubleSpinBox_ration_min.setObjectName("doubleSpinBox_ration_min")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_ration_min)
        self.doubleSpinBox_ration_max = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleSpinBox_ration_max.setProperty("value", 2.0)
        self.doubleSpinBox_ration_max.setObjectName("doubleSpinBox_ration_max")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_ration_max)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.doubleSpinBox_step_size = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleSpinBox_step_size.setProperty("value", 0.1)
        self.doubleSpinBox_step_size.setObjectName("doubleSpinBox_step_size")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_step_size)
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.spinBox_Ns = QtWidgets.QSpinBox(parent=self.groupBox)
        self.spinBox_Ns.setObjectName("spinBox_Ns")
        self.horizontalLayout_4.addWidget(self.spinBox_Ns)
        spacerItem3 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_5.addItem(spacerItem4)
        self.pushButton_compute_parameters = QtWidgets.QPushButton(
            parent=self.tab_patient
        )
        self.pushButton_compute_parameters.setCheckable(True)
        self.pushButton_compute_parameters.setObjectName(
            "pushButton_compute_parameters"
        )
        self.horizontalLayout_5.addWidget(self.pushButton_compute_parameters)
        spacerItem5 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab_patient)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        spacerItem6 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_13.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.doubleSpinBox_dw = QtWidgets.QDoubleSpinBox(parent=self.groupBox_2)
        self.doubleSpinBox_dw.setMaximum(9999.99)
        self.doubleSpinBox_dw.setObjectName("doubleSpinBox_dw")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_dw)
        spacerItem7 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_12.addItem(spacerItem8)
        self.pushButton_valid_test_params = QtWidgets.QPushButton(
            parent=self.tab_patient
        )
        self.pushButton_valid_test_params.setCheckable(True)
        self.pushButton_valid_test_params.setObjectName("pushButton_valid_test_params")
        self.horizontalLayout_12.addWidget(self.pushButton_valid_test_params)
        spacerItem9 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.tab_patient)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem10 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem10)
        self.lineEdit_test_id = QtWidgets.QLineEdit(parent=self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_test_id.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_test_id.setSizePolicy(sizePolicy)
        self.lineEdit_test_id.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.lineEdit_test_id.setObjectName("lineEdit_test_id")
        self.horizontalLayout_2.addWidget(self.lineEdit_test_id)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem11 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_6.addItem(spacerItem11)
        self.pushButton_ctrl_test = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_ctrl_test.setCheckable(True)
        self.pushButton_ctrl_test.setObjectName("pushButton_ctrl_test")
        self.horizontalLayout_6.addWidget(self.pushButton_ctrl_test)
        spacerItem12 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem13 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem13)
        self.tabWidget.addTab(self.tab_patient, "")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_test)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        spacerItem14 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem19)
        self.lineEdit_test_name = QtWidgets.QLineEdit(parent=self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_test_name.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_test_name.setSizePolicy(sizePolicy)
        self.lineEdit_test_name.setObjectName("lineEdit_test_name")
        self.horizontalLayout_17.addWidget(self.lineEdit_test_name)
        self.pushButton_lock = QtWidgets.QPushButton(parent=self.tab_test)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pushButton_lock.sizePolicy().hasHeightForWidth()
        )
        self.pushButton_lock.setSizePolicy(sizePolicy)
        self.pushButton_lock.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/lock_open.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        icon.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/lock_close.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.On,
        )
        self.pushButton_lock.setIcon(icon)
        self.pushButton_lock.setCheckable(True)
        self.pushButton_lock.setObjectName("pushButton_lock")
        self.horizontalLayout_17.addWidget(self.pushButton_lock)
        spacerItem20 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_17.addItem(spacerItem20)
        self.pushButton_record = QtWidgets.QPushButton(parent=self.tab_test)
        self.pushButton_record.setEnabled(True)
        self.pushButton_record.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/record.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        icon1.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/record_g.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.On,
        )
        self.pushButton_record.setIcon(icon1)
        self.pushButton_record.setCheckable(True)
        self.pushButton_record.setObjectName("pushButton_record")
        self.horizontalLayout_17.addWidget(self.pushButton_record)
        self.pushButton_play_pause = QtWidgets.QPushButton(parent=self.tab_test)
        self.pushButton_play_pause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/play.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        icon2.addPixmap(
            QtGui.QPixmap(
                "../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../../home/vscode/.designer/backup/icons/pause.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.On,
        )
        self.pushButton_play_pause.setIcon(icon2)
        self.pushButton_play_pause.setCheckable(True)
        self.pushButton_play_pause.setObjectName("pushButton_play_pause")
        self.horizontalLayout_17.addWidget(self.pushButton_play_pause)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.tab_test)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        spacerItem21 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_8.addItem(spacerItem21)
        self.pushButton_plot = QtWidgets.QPushButton(parent=self.tab_test)
        self.pushButton_plot.setCheckable(True)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout_8.addWidget(self.pushButton_plot)
        self.pushButton_refresh = QtWidgets.QPushButton(parent=self.tab_test)
        self.pushButton_refresh.setText("")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_8.addWidget(self.pushButton_refresh)
        spacerItem22 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_8.addItem(spacerItem22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(parent=self.tab_test)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        spacerItem23 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_10.addItem(spacerItem23)
        self.label_quaterion_offset = QtWidgets.QLabel(parent=self.tab_test)
        self.label_quaterion_offset.setText("")
        self.label_quaterion_offset.setObjectName("label_quaterion_offset")
        self.horizontalLayout_10.addWidget(self.label_quaterion_offset)
        spacerItem24 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_10.addItem(spacerItem24)
        self.pushButton_set_init_imus_orientations = QtWidgets.QPushButton(
            parent=self.tab_test
        )
        self.pushButton_set_init_imus_orientations.setObjectName(
            "pushButton_set_init_imus_orientations"
        )
        self.horizontalLayout_10.addWidget(self.pushButton_set_init_imus_orientations)
        self.checkBox_compensate = QtWidgets.QCheckBox(parent=self.tab_test)
        self.checkBox_compensate.setObjectName("checkBox_compensate")
        self.horizontalLayout_10.addWidget(self.checkBox_compensate)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.tab_test)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3D_visu = QtWidgets.QFrame(parent=self.tab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_3D_visu.sizePolicy().hasHeightForWidth()
        )
        self.frame_3D_visu.setSizePolicy(sizePolicy)
        self.frame_3D_visu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3D_visu.setObjectName("frame_3D_visu")
        self.verticalLayout_5.addWidget(self.frame_3D_visu)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_test)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.label_quaternions_values = QtWidgets.QLabel(parent=self.tab_test)
        self.label_quaternions_values.setText("")
        self.label_quaternions_values.setObjectName("label_quaternions_values")
        self.horizontalLayout_9.addWidget(self.label_quaternions_values)
        spacerItem25 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_9.addItem(spacerItem25)
        spacerItem26 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_9.addItem(spacerItem26)
        self.label_angles_values = QtWidgets.QLabel(parent=self.tab_test)
        self.label_angles_values.setText("")
        self.label_angles_values.setObjectName("label_angles_values")
        self.horizontalLayout_9.addWidget(self.label_angles_values)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_replay_record = QtWidgets.QWidget()
        self.tab_replay_record.setObjectName("tab_replay_record")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_replay_record)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_21 = QtWidgets.QLabel(parent=self.tab_replay_record)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_19.addWidget(self.label_21)
        spacerItem27 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_19.addItem(spacerItem27)
        self.comboBox_replay_test_name = QtWidgets.QComboBox(
            parent=self.tab_replay_record
        )
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.comboBox_replay_test_name.sizePolicy().hasHeightForWidth()
        )
        self.comboBox_replay_test_name.setSizePolicy(sizePolicy)
        self.comboBox_replay_test_name.setEditable(True)
        self.comboBox_replay_test_name.setObjectName("comboBox_replay_test_name")
        self.horizontalLayout_19.addWidget(self.comboBox_replay_test_name)
        self.pushButton_replay_refresh = QtWidgets.QPushButton(
            parent=self.tab_replay_record
        )
        self.pushButton_replay_refresh.setText("")
        self.pushButton_replay_refresh.setObjectName("pushButton_replay_refresh")
        self.horizontalLayout_19.addWidget(self.pushButton_replay_refresh)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_replay_record)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_chose_angle = QtWidgets.QComboBox(parent=self.tab_replay_record)
        self.comboBox_chose_angle.setObjectName("comboBox_chose_angle")
        self.comboBox_chose_angle.addItem("")
        self.comboBox_chose_angle.addItem("")
        self.comboBox_chose_angle.addItem("")
        self.comboBox_chose_angle.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_chose_angle)
        self.label = QtWidgets.QLabel(parent=self.tab_replay_record)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_qoffset_index = QtWidgets.QSpinBox(parent=self.tab_replay_record)
        self.spinBox_qoffset_index.setMinimum(-1)
        self.spinBox_qoffset_index.setMaximum(60000000)
        self.spinBox_qoffset_index.setObjectName("spinBox_qoffset_index")
        self.horizontalLayout.addWidget(self.spinBox_qoffset_index)
        spacerItem28 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem28)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem29 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_20.addItem(spacerItem29)
        self.pushButton_plot_replay = QtWidgets.QPushButton(
            parent=self.tab_replay_record
        )
        self.pushButton_plot_replay.setObjectName("pushButton_plot_replay")
        self.horizontalLayout_20.addWidget(self.pushButton_plot_replay)
        spacerItem30 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_20.addItem(spacerItem30)
        self.pushButton_plot_replay_clear = QtWidgets.QPushButton(
            parent=self.tab_replay_record
        )
        self.pushButton_plot_replay_clear.setObjectName("pushButton_plot_replay_clear")
        self.horizontalLayout_20.addWidget(self.pushButton_plot_replay_clear)
        self.verticalLayout_10.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        spacerItem31 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_10.addItem(spacerItem31)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem32 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_14.addItem(spacerItem32)
        self.pushButton_export_csv = QtWidgets.QPushButton(
            parent=self.tab_replay_record
        )
        self.pushButton_export_csv.setObjectName("pushButton_export_csv")
        self.horizontalLayout_14.addWidget(self.pushButton_export_csv)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_replay_record, "")
        self.tab_ctrl_sensors = QtWidgets.QWidget()
        self.tab_ctrl_sensors.setObjectName("tab_ctrl_sensors")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_ctrl_sensors)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.tab_ctrl_sensors)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_reset_all_triggers = QtWidgets.QPushButton(
            parent=self.groupBox_4
        )
        self.pushButton_reset_all_triggers.setObjectName(
            "pushButton_reset_all_triggers"
        )
        self.horizontalLayout_3.addWidget(self.pushButton_reset_all_triggers)
        spacerItem33 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem33)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem34 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_4.addItem(spacerItem34)
        self.tabWidget.addTab(self.tab_ctrl_sensors, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        DockWidget_sequence.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget_sequence)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.pushButton_compute_parameters.toggled["bool"].connect(self.groupBox_2.setEnabled)  # type: ignore
        self.pushButton_valid_test_params.toggled["bool"].connect(self.groupBox_3.setEnabled)  # type: ignore
        self.pushButton_compute_parameters.toggled["bool"].connect(self.groupBox.setDisabled)  # type: ignore
        self.pushButton_valid_test_params.toggled["bool"].connect(self.groupBox_2.setDisabled)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DockWidget_sequence)

    def retranslateUi(self, DockWidget_sequence):
        _translate = QtCore.QCoreApplication.translate
        DockWidget_sequence.setWindowTitle(
            _translate("DockWidget_sequence", "Sequence settings")
        )
        self.groupBox.setTitle(_translate("DockWidget_sequence", "Test settings"))
        self.label_7.setText(_translate("DockWidget_sequence", "Move ID:"))
        self.lineEdit_move_id.setText(
            _translate("DockWidget_sequence", "<MOVE_TEST_ID>")
        )
        self.label_12.setText(_translate("DockWidget_sequence", "Visit"))
        self.comboBox_visit.setItemText(0, _translate("DockWidget_sequence", "0"))
        self.comboBox_visit.setItemText(1, _translate("DockWidget_sequence", "1"))
        self.label_4.setText(_translate("DockWidget_sequence", "Shoulder width (cm):"))
        self.label_5.setText(
            _translate("DockWidget_sequence", "Ratio range (min, max):")
        )
        self.label_6.setText(_translate("DockWidget_sequence", "Step size:"))
        self.label_8.setText(_translate("DockWidget_sequence", "N_step:"))
        self.pushButton_compute_parameters.setText(
            _translate("DockWidget_sequence", "Compute parameters")
        )
        self.groupBox_2.setTitle(_translate("DockWidget_sequence", "Test parameters"))
        self.label_15.setText(_translate("DockWidget_sequence", "Current test:"))
        self.label_2.setText(_translate("DockWidget_sequence", "Door width (cm):"))
        self.pushButton_valid_test_params.setText(
            _translate("DockWidget_sequence", "Valid test parameters")
        )
        self.groupBox_3.setTitle(
            _translate("DockWidget_sequence", "Test lauch control")
        )
        self.label_13.setText(_translate("DockWidget_sequence", "TEST_ID:"))
        self.pushButton_ctrl_test.setText(
            _translate("DockWidget_sequence", "Start test")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_patient),
            _translate("DockWidget_sequence", "Settings"),
        )
        self.label_20.setText(_translate("DockWidget_sequence", "Test name:"))
        self.label_9.setText(_translate("DockWidget_sequence", "Controls:"))
        self.pushButton_plot.setText(_translate("DockWidget_sequence", "Plot"))
        self.label_10.setText(_translate("DockWidget_sequence", "Offset:"))
        self.pushButton_set_init_imus_orientations.setText(
            _translate("DockWidget_sequence", "Set Init Orientation")
        )
        self.checkBox_compensate.setText(
            _translate("DockWidget_sequence", "Compensate")
        )
        self.tabWidget_2.setTabText(
            self.tabWidget_2.indexOf(self.tab),
            _translate("DockWidget_sequence", "3D scene"),
        )
        self.tabWidget_2.setTabText(
            self.tabWidget_2.indexOf(self.tab_2),
            _translate("DockWidget_sequence", "2D graph"),
        )
        self.label_11.setText(_translate("DockWidget_sequence", "Real time:"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_test),
            _translate("DockWidget_sequence", "Visualization"),
        )
        self.label_21.setText(_translate("DockWidget_sequence", "Test name:"))
        self.label_3.setText(_translate("DockWidget_sequence", "Angle type:"))
        self.comboBox_chose_angle.setItemText(
            0, _translate("DockWidget_sequence", "yaw")
        )
        self.comboBox_chose_angle.setItemText(
            1, _translate("DockWidget_sequence", "pitch")
        )
        self.comboBox_chose_angle.setItemText(
            2, _translate("DockWidget_sequence", "roll")
        )
        self.comboBox_chose_angle.setItemText(
            3, _translate("DockWidget_sequence", "norm_acc")
        )
        self.label.setText(_translate("DockWidget_sequence", "qoffset index"))
        self.pushButton_plot_replay.setText(_translate("DockWidget_sequence", "Plot"))
        self.pushButton_plot_replay_clear.setText(
            _translate("DockWidget_sequence", "Clear")
        )
        self.pushButton_export_csv.setText(
            _translate("DockWidget_sequence", "export csv")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_replay_record),
            _translate("DockWidget_sequence", "Replay"),
        )
        self.groupBox_4.setTitle(_translate("DockWidget_sequence", "Triggers sensors"))
        self.pushButton_reset_all_triggers.setText(
            _translate("DockWidget_sequence", "Reset triggers")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_ctrl_sensors),
            _translate("DockWidget_sequence", "Sensor settings"),
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DockWidget_sequence = QtWidgets.QDockWidget()
    ui = Ui_DockWidget_sequence()
    ui.setupUi(DockWidget_sequence)
    DockWidget_sequence.show()
    sys.exit(app.exec())
