# Form implementation generated from reading ui file 'IMU_manager_line.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 61)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_id = QtWidgets.QLabel(parent=Form)
        self.label_id.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_id.setObjectName("label_id")
        self.horizontalLayout.addWidget(self.label_id)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_name.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_name.setSizePolicy(sizePolicy)
        self.lineEdit_name.setInputMask("")
        self.lineEdit_name.setText("")
        self.lineEdit_name.setReadOnly(False)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.lineEdit_mac_address = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_mac_address.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_mac_address.setSizePolicy(sizePolicy)
        self.lineEdit_mac_address.setInputMask("")
        self.lineEdit_mac_address.setObjectName("lineEdit_mac_address")
        self.horizontalLayout.addWidget(self.lineEdit_mac_address)
        self.lineEdit_ip_address = QtWidgets.QLineEdit(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_ip_address.sizePolicy().hasHeightForWidth()
        )
        self.lineEdit_ip_address.setSizePolicy(sizePolicy)
        self.lineEdit_ip_address.setObjectName("lineEdit_ip_address")
        self.horizontalLayout.addWidget(self.lineEdit_ip_address)
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMinimum(49152)
        self.spinBox.setMaximum(65535)
        self.spinBox.setProperty("value", 64344)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.comboBox_rf_port = QtWidgets.QComboBox(parent=Form)
        self.comboBox_rf_port.setObjectName("comboBox_rf_port")
        self.comboBox_rf_port.addItem("")
        self.comboBox_rf_port.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_rf_port)
        self.checkBox_connection = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_connection.setObjectName("checkBox_connection")
        self.horizontalLayout.addWidget(self.checkBox_connection)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.commandLinkButton.sizePolicy().hasHeightForWidth()
        )
        self.commandLinkButton.setSizePolicy(sizePolicy)
        self.commandLinkButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.commandLinkButton.setText("")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_id.setText(_translate("Form", "0"))
        self.lineEdit_mac_address.setText(_translate("Form", "68:27:19:F9:0E:C4"))
        self.lineEdit_ip_address.setInputMask(_translate("Form", "000.000.000.000"))
        self.lineEdit_ip_address.setText(_translate("Form", "127.0.0.1"))
        self.comboBox_rf_port.setItemText(0, _translate("Form", "/dev/rfcom0"))
        self.comboBox_rf_port.setItemText(1, _translate("Form", "New Item"))
        self.checkBox_connection.setText(_translate("Form", "I/O"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
